serviceName: "ui"
namespace: "retail-store"
replicaCount: 2

image:
  repository: public.ecr.aws/aws-containers/retail-store-sample-ui
  tag: "1.2.4"

app:
  port: 8080
  healthPath: "/actuator/health"
  readyPath: "/actuator/health"
  env:
    - name: JAVA_OPTS
      value: "-XX:MaxRAMPercentage=75.0 -Djava.security.egd=file:/dev/urandom"
    - name: SERVER_TOMCAT_ACCESSLOG_ENABLED
      value: "true"
    - name: RETAIL_UI_ENDPOINTS_CATALOG
      value: "http://catalog:8080"
    - name: RETAIL_UI_ENDPOINTS_CARTS
      value: "http://cart:8080"
    - name: RETAIL_UI_ENDPOINTS_ORDERS
      value: "http://order:8080"
    - name: RETAIL_UI_ENDPOINTS_CHECKOUT
      value: "http://checkout:8080"

service:
  port: 80

ingress:
  enabled: true
  className: "alb"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  hosts:
    - paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 750m
    memory: 512Mi
  requests:
    cpu: 375m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 8
  targetCPUUtilizationPercentage: 70