serviceName: "cart"
namespace: "retail-store"
replicaCount: 2

image:
  repository: public.ecr.aws/aws-containers/retail-store-sample-cart
  tag: "1.2.4"

app:
  port: 8080
  healthPath: "/actuator/health"
  readyPath: "/actuator/health"
  env:
    - name: SERVER_TOMCAT_ACCESSLOG_ENABLED
      value: "true"
    - name: RETAIL_CART_PERSISTENCE_PROVIDER
      value: "dynamodb"

service:
  port: 80

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 8
  targetCPUUtilizationPercentage: 70

database:
  dynamodb:
    enabled: true
  redis:
    host: ""
    password: ""