name: Destroy Infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to destroy'
        required: true
        type: choice
        options:
        - dev
        - staging
        - prod
      confirm_destroy:
        description: 'Type "DESTROY" to confirm'
        required: true
        type: string

env:
  AWS_REGION: us-east-1

jobs:
  destroy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Validate confirmation
      run: |
        if [ "${{ github.event.inputs.confirm_destroy }}" != "DESTROY" ]; then
          echo "❌ Confirmation failed. You must type 'DESTROY' to proceed."
          exit 1
        fi
        echo "✅ Confirmation validated"

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.0

    - name: Terraform Destroy
      run: |
        cd environments/${{ github.event.inputs.environment }}
        terraform init
        terraform destroy -auto-approve
      env:
        TF_VAR_postgresql_password: ${{ secrets.POSTGRESQL_PASSWORD }}
        TF_VAR_mysql_password: ${{ secrets.MYSQL_PASSWORD }}
        TF_VAR_redis_auth_token: ${{ secrets.REDIS_AUTH_TOKEN }}
        TF_VAR_github_org: ${{ github.repository_owner }}
        TF_VAR_github_repo: ${{ github.event.repository.name }}